### ISSUE TITLE
New Folder & Backup

### ISSUE THREAD

**Issue by ThomasDebnt** [conceptualspace/yet-another-speed-dial#41] opened 2021-10-26 14:54 UTC
Hello,

Will it be possible to reorganize the folder? Because at the moment each new folder is added at the end and we don't know how to move it.
I'm not sure if it's a good idea to use the browser extension to choose which folder you want to put the new bookmarks in.

I'm not sure if it's possible to make a backup of our configuration?

Thanks for the answer and also for this great extension!

**Comment by conceptualspace** [comment] 2021-11-03 20:26
thanks @ThomasDebnt, sorting folders is in the works and should be ready soon (duplicate of issue #34)

as far as using YASD to create folders, as @SerafDosSantos pointed out, under the hood YASD is just using the browser's folders and bookmarks, so you can export and back them up on the browser side. yasd uses its own local storage for the thumbnails and settings. an export option for these is also coming soon :smile:

**Closed by conceptualspace** 2021-11-03 20:26 UTC
