### ISSUE TITLE
Feature Request: Change Icon Size

### ISSUE THREAD

**Issue by tomatohorse** [conceptualspace/yet-another-speed-dial#69] opened 2022-10-28 17:36 UTC
This extension is great! I appreciate the work you have done to create it for us all to use.

I do have one request: I'd really like to be able to change the size of the icons. (They're too big currently, at least for me). Some kind of slider with a min / max range would be quite nice. 

Thanks for considering

**Comment by joshkerr** [comment] 2022-11-03 22:22
I would love to see a slider that can (in realtime) change the icon size, one for the padding around the icons and within the icon itself, and one for adjusting the number of columns.

**Comment by conceptualspace** [comment] 2022-11-03 22:45
thanks, yeah it's definitely something many have asked for and i'll try to get into the next release. i might also add a ratio option (wide or square)

closing this as duplicate of #57

**Closed by conceptualspace** 2022-11-03 22:45 UTC
