### ISSUE TITLE
Black / empty page

### ISSUE THREAD

**Issue by sunjaxx** [conceptualspace/yet-another-speed-dial#56] opened 2022-02-19 08:05 UTC
This started few months ago. Most of the time, when I open Chrome, an SD tab is opened as expected, but it just shows a black / empty page. 

![Untitled](https://user-images.githubusercontent.com/30780852/154792629-1ea8e5e4-d4fd-4728-b4f8-74d857c403d5.png)

If I *then* open a new tab, tabs are shown correctly. 
Any ideas?
Thanks!

**Comment by conceptualspace** [comment] 2022-02-19 16:31
Thank you for the report. When you're on the black page, could you please open the dev console (Ctrl+Shift+i on Windows) and copy any error messages you see?

Please also check the extensions settings page (chrome://extensions) - under Yet Another Speed Dial should be a link that says "Inspect views: background page". Click that and copy any error messages

If you prefer to share the log with me directly, you can send it to dev@conceptualspace.net and I'll look into it. Thanks!

**Comment by sunjaxx** [comment] 2022-02-19 17:03
Thanks. The error I see in the log is: 

**index.html:1 Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.**

(By the way, on the extensions settings page, under Yet Another Speed Dial, I don't see the link you mention....)

**Comment by conceptualspace** [comment] 2022-02-19 17:09
Thanks, looking into it

On the settings page you might have to click "Details" first, and then should be a link to "Background page". Let me know if you find it and anything is there

**Comment by sunjaxx** [comment] 2022-02-19 19:07
thanks, found it, I had to click on "developer mode" for that link to appear: it says "no issues detected so far".

**Comment by conceptualspace** [comment] 2022-02-19 19:31
ok. thanks again for your help. i think i have a fix, am testing the changes

question: do you have a lot of bookmarks in YASD? can you give me a rough idea?

and just to be clear, this usually happens when you first start your browser, and then subsequent new tabs are OK right?

**Comment by conceptualspace** [comment] 2022-02-20 03:18
im not able to replicate the problem to test unfortunately, but i made some changes in v2.1.7 that might help. please let me know (chrome should update in a day or so)

for reference, other extension with similar issues:
https://github.com/MetaMask/metamask-extension/issues/9407

**Comment by sunjaxx** [comment] 2022-02-21 07:29
I am now on 2.1.7 but have the same issue. :-(

> question: do you have a lot of bookmarks in YASD? can you give me a rough idea?

I have 16 folders: 25 bookmarks in the first/default one, and ~140 bookmarks overall. Is that too much / the reason?

**Comment by conceptualspace** [comment] 2022-02-21 16:14
ok, thanks. can you send me any log messages again? they might be slightly different from this version but will help me confirm the cause. can you also please confirm your OS and browser version?

if you have any other extensions installed you could also try disabling them and restarting the browser to see if there's any difference.

i don't think it's related to the number of bookmarks, many users have thousands. sorry for the inconvenience.. i think its a bug in Chrome but have some ideas to work around it

**Comment by sunjaxx** [comment] 2022-02-21 17:06
I'm on Win10 and Chrome Version 98.0.4758.102 (Official Build) (64-bit). 

I get this:

`Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform
A page or script is accessing at least one of navigator.userAgent, navigator.appVersion, and navigator.platform. Starting in Chrome 101, the amount of information available in the User Agent string will be reduced.
To fix this issue, replace the usage of navigator.userAgent, navigator.appVersion, and navigator.platform with feature detection, progressive enhancement, or migrate to navigator.userAgentData.
Note that for performance reasons, only the first access to one of the properties is shown.
1 source
Sortable.min.js:1
Learn more: User-Agent String Reduction`

I have others extensions. when I disable [this one](https://chrome.google.com/webstore/detail/apk-downloader/idkigghdjmipnppaeahkpcoaiphjdccm), the problem seems to disappear...!

**Comment by conceptualspace** [comment] 2022-03-23 17:08
just documenting here for posterity, it seems that for some reason (related to the other extension) the background message listener wasn't ready/able to respond to the message from the new tab page. this is likely to get refactored for manifest v3 anyway so closing for now. if anyone experiences similar issues please feel free to reopen

**Closed by conceptualspace** 2022-03-23 17:08 UTC

**Comment by conceptualspace** [comment] 2022-07-08 19:52
:( it might be a bug in chrome. i think we will get around it migrating to manifest v3, but that is still a work in progress
