### ISSUE TITLE
Favicons not showing on speed dial?

### ISSUE THREAD

**Issue by DaveWalk1** [conceptualspace/yet-another-speed-dial#1] opened 2019-07-06 12:59 UTC
Hi there,
Some websites' icons are blank in my new tabs. See my image below:

![image](https://user-images.githubusercontent.com/25713392/60756525-4b7ae200-9fcc-11e9-8f71-734f60e2aabe.png)

**Comment by conceptualspace** [comment] 2019-07-09 04:16
the extension does its best to find a suitable image from the page in addition to a screenshot, but if it cannot it shows the semi-transparent image on the right. the white and blank images are unusual though -- would you mind sharing the URLs for those sites so i can look into it further?

also screenshots are currently only generated when you bookmark a site or right-click and select "add to speed dial"; they are not generated if you copy a bookmark from another folder into the speed dial folder (since the site has to be open so we can capture the screen). this should be resolved in the next version or so as i refine the technique to grab the image in the background :)

**Comment by conceptualspace** [comment] 2019-07-09 04:25
i've confirmed the issue with both of those icons are on the sites themselves -- specifically the following code on the literary hub website instructs sites to use the blank icon:

<meta property="og:image" content="https://s0.wp.com/i/blank.jpg" />

and similarily, the boston globe references an image that is corrupt:

https://www.bostonglobe.com/pf/resources/images/logo-bg.jpg

so if you were to, for example, share a link to either site on facebook or twitter, it would use the same blank or broken images.

so what you can do is right-click the speed dial, select edit, and then choose the screenshot as your icon instead.

**Closed** 2019-07-09 14:24 UTC

**Comment by DaveWalk1** [comment] 2019-07-18 16:43
Thanks for this, you cleared things up for me! Follow up question / enhancement: could we select an outside image? Or a portion of a screenshot? (Or even the favicon, but I assume that's too lowrez..?)

**Comment by conceptualspace** [comment] 2019-07-18 16:45
on the todo list :)
